import google.generativeai as genai
import plotly.io as pio
import PIL.Image
import io
import os
#import cairosvg

def get_api_key_local():
    """
    This function retrieves the Gemini API key from ~/Documents/Gemini/mcbroken-forecasting.txt.

    Returns:
    - str: The Gemini API key
    """
    # Define the path to the file containing the API key
    api_key_path = os.path.expanduser("~/Documents/Gemini/mcbroken-forecasting.txt")
    
    # Open the file and read the API key
    with open(api_key_path, 'r') as file:
        api_key = file.read().strip()  # Remove any leading/trailing whitespace
    
    return api_key

def get_api_key_aws():
    """
    Load the Gemini API key from a secure location in AWS.
    
    Returns:
    - str: The Gemini API key
    """
    import boto3
    # S3 details
    s3 = boto3.client('s3')
    bucket = 'mcbroken-forecasting-api-keys'  # S3 bucket name for storing API keys
    key = 'mcbroken-forecasting.txt'  # File name in S3

    # Load data from S3
    obj = s3.get_object(Bucket=bucket, Key=key)
    api_key = obj['Body'].read().decode('utf-8').strip()  # Read and decode the API key

    return api_key

def get_image_description(chart, api_key):
    """
    This function generates a description of the chart using Gemini API.
    
    Parameters:
    - chart (plotly.graph_objects.Figure): The chart to be described.
    - api_key (str): Your Gemini API key.

    Returns:
    - str: The generated description of the image.
    """
    
    print("Starting function")
    print("Type for figure:", type(chart))

    # # Load the image into pillow (PIL) format from the Plotly figure
    # # Save the figure to a bytes buffer
    # buffer = io.BytesIO()
    # # Use Plotly's image export function to save the figure as a PNG image
    # pio.write_image(chart, buffer, format='png')
    # # Move the cursor to the beginning of the buffer
    # buffer.seek(0)
    # print("Buffer created for image export.")

    # # Open the image using PIL
    # # Note: The buffer is passed directly to PIL to avoid saving the image to disk
    # image = PIL.Image.open(buffer)
    # print("Image opened using PIL.")

    # Save to disk as Test.png
    pio.write_image(chart, 'Test.png', format='png')
    print("Figure saved as Test.png.")
    # Open the saved image using PIL
    image = PIL.Image.open('Test.png')
    print("Image opened from Test.png using PIL.")

    # # Save image to disk as Test.svg
    # pio.write_image(chart, 'Test.svg', format='svg')
    # print("Figure saved as Test.svg.")
    # # Convert the SVG to PNG using PIL
    # # Convert SVG to PNG
    # cairosvg.svg2png(url='Test.svg', write_to='Test.png')
    # print("SVG converted to PNG and saved as Test.png.")
    # # Open the converted PNG image using PIL
    # image = PIL.Image.open('Test.png')
    # print("Image opened from Test.png using PIL.")

    # Initialize the Gemini client
    client = genai.Client(api_key=api_key)
    print("Gemini client initialized.")

    # Engineered prompt
    prompt = """
        Describe what this plot shows, in two sentences.

        Sentence 1: Describe what the forecast shows, particularly in terms of trends in a direction or no trend. "The exponential smoothing/ARIMA/Prophet forecast shows..."
        
        Sentence 2: Describe what the confidence intervals indicate. Qualitatively, how large are they? Are they growing, shrinking or staying the same?

        You don't need to describe the overall plot, as the audience can see the title and the broader context as this is just one part of a larger dashboard - just cover what the data shows. Example of what context to include/not include: "The ARIMA forecast shows fluctuating revenue losses, generally trending downward..." is good, but "The ARIMA forecast shows fluctuating revenue losses from broken McDonald's ice cream machines, generally trending downward..." is not good.

        Be concise.
    """

    # Generate content using the Gemini model
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=[image, prompt] # text prompt after image
    )
    print("Content generated by Gemini model.")

    return response.text

def generate_description_html(description_text):
    """
    Generates a basic HTML string to display the provided description text.

    Args:
    - description_text (str): The text to be displayed in the HTML description.

    Returns:
    - str: A string containing the HTML content with the description text.
    """
    html_content = f"""<!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI-Generated Description</title>
    <style>
        body {{
            font-family: sans-serif; /* Adjust to match Google Sites font */
            margin: 0;
            padding: 10px;
            word-wrap: break-word; /* Prevent long text from breaking layout */
        }}
        p {{
            font-size: 1em; /* Adjust as needed */
            color: #333; /* Adjust as needed */
            line-height: 1.5; /* Adjust as needed */
        }}
    </style>
    </head>
    <body>
    <p>{description_text}</p>
    </body>
    </html>
    """
    return html_content

def save_description_html_aws(client, bucket, description_html, filename):
    import boto3
    # Save description as HTML to temporary Lambda storage
    html_output = '/tmp/' + filename + '.html'
    with open(html_output, 'w') as f:
        f.write(description_html)

    # Upload HTML to S3 and make it publicly accessible
    client.upload_file(html_output, bucket, filename, ExtraArgs={'ContentType': 'text/html', 'ACL': 'public-read'})

    # Return the S3 link
    return {
        'statusCode': 200,
        'body': f"Forecast saved to: https://{bucket}.s3.amazonaws.com/{filename}"
    }

def save_description_html_local(description_html, filename):
    """
    Save description HTML to the Graphics directory with the specified filename.
    
    Args:
        description_html (str): The HTML content to save.
        filename (str): The filename to save the HTML as (should include .html extension).
    
    Returns:
        str: The absolute path to the saved file.
    """
    # Save plot as HTML to the Graphics directory
    if not os.path.exists("Graphics"):
        os.makedirs("Graphics")
    output_path = f"Graphics/{filename}"
    with open(output_path, 'w') as f:
        f.write(description_html)
    print(f"Description saved to: {os.path.abspath(output_path)}")
    return os.path.abspath(output_path) 
